[package]
name = "rusty"
version = "0.1.0"
authors = ["zrauf <zrauf@sfu.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
